---
title: "How to use it with Lavaan"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to use it with Lavaan}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, include = FALSE}
library(Lmisc)
library(dplyr)
library(ggplot2)
library(lavaan)
library(ggdag)
```



```
library(Lmisc)
library(dplyr)
library(ggplot2)
library(lavaan)
```

# Specify the model

```{r}
# Load the dataset. This dataset was taken from lavaan 6.2.1. Versions >0.7 have removed it.
data("FacialBurns", package = "Lmisc")
```


We specify the model first. This is just a toy model for illustrative purposes.

```{r}
model <- "
HADS ~ Age
HADS ~ Sex
HADS ~ TBSA
TBSA ~ Age
TBSA ~ Sex
"
```


```{r}
fit_model <- sem(
  model = model,
  data = FacialBurns,
  missing = "fiml"
)
summary(fit_model)
```


# Dagify the model
```{r}
dag <- ggdag::dagify(
  HADS ~ Age,
  HADS ~ Sex,
  HADS ~ TBSA,
  TBSA ~ Age,
  TBSA ~ Sex,
  outcome = "TBSA",
  coords = list(
    x = c(
      TBSA = 0,
      HADS = 4,
      Age = 2,
      Sex = 2
    ),
    y = c(
      HADS = 0,
      TBSA = 0,
      Age = 1,
      Sex = -1
    )
  ),
  labels = c(
    # If you need to change the names, specify the labels here
    HADS = "HADS",
    TBSA = "TBSA",
    Age = "Age",
    Sex = "Sex"
  )
)


tidy_dag <- ggdag::tidy_dagitty(dag)
```

# Create nodes and edges dataframes

```{r}

nodes <- tidy_dag$data %>%
  filter(!duplicated(name)) %>%
  dplyr::transmute(
    node_id = name,
    x = x,
    y = y,
    label = label
  ) %>%
  mutate(node_id = label)

# If you need curved paths
edges <- tidy_dag$data %>%
  mutate(
    curvature = case_when(
      name == "Sex" & to == "HADS" ~ 1,
      TRUE ~ 0 # default: straight
    ) 
  ) |> 
  mutate(
    curvature_amount = case_when(
      name == "Sex" & to == "HADS" ~ 0.3,
      TRUE ~ 0 
    ) 
  )

```


# Extract the parameters

```{r}
parameters_fit_model <- modify_parameter_estimates(
  df = parameterestimates(
    fit_model,
    standardized = F
  ),
  round_digits = 2
)


temp <- data.frame(
  # Extract only the regression paths
  parameters_fit_model[
    parameters_fit_model$op == "~", 
    ]
)


edges <- left_join(
  x = edges,
  y = temp,
  by = join_by(
    # rhs =  right hand side = where the path starts
    # lhs = left hand side = where the path ends
    name == rhs, 
    to == lhs
  )
)

# Rename and keep only what we need
edges <- edges %>%
  filter(!is.na(to)) %>%
  transmute(
    from = name,
    to = to,
    curvature = curvature,
    curvature_amount = curvature_amount,
    pvalue = pvalue,
    est = est,
    ci.lower = ci.lower,
    ci.upper = ci.upper
  )

edges <- edges |> 
  mutate(
    hjust = case_when(
      from == "Sex" & to == "HADS" ~ 0.5,
      .default = 0.5
    )
  ) |> 
  mutate(
    vjust = case_when(
      from == "Sex" & to == "HADS" ~ 0.5,
      .default = 0.5
    )
  ) |> 
  mutate(
    gap = case_when(
      from == "Sex" & to == "HADS" ~ -0.5,
      .default = -1
    )
  )


```


# Plot the estimates

```{r}
plot_dag(
  nodes = nodes,
  edges = edges,
  label_size = 10,
  label_size_unit = "pt",
  text_size = 4,
  xlim = c(-0.5, 4.4),
  ylim = c(-1.5, 1.5)
)
```


